#!/usr/bin/env bash

read -p "Enter the hidden files" -a files
git rm --cached $files

read -p "commit message" commit
git commit -m "$commit"

read -p "give the branch name" branch
git checkout "$branch"
if [[ "$(git branch --show-current)" == "$branch" ]]; then
    git push origin "$branch"
else
    echo "you're not in the same branch" >&2
fi
