#!/usr/bin/env bash

trap 'echo "Error occurred"' ERR
trap 'echo "Done!!!!"' EXIT

if [ ! -d ".git" ]; then
    git init
fi

read -p "Files to add (* for all): " -a files

if [[ "${files[0]}" == "*" ]]; then
    git add .
else
    git add "${files[@]}"
fi

read -p "Commit message: " commit
git commit -m "$commit"

read -p "Branch name: " branch

git switch "$branch" 2>/dev/null ||
git switch -c "$branch"

read -p "Push to remote? (yes/no): " _push

if [[ $_push == "yes" &&
      "$(git branch --show-current)" == "$branch" ]]
then
    git push origin "$branch"
else
    echo "Local checkpoint only"
fi
