#!/usr/bin/env bash

git init
git add -A
git commit -m "Deleted unused files"

read -p "give the branch name" branch
git checkout "$branch"
if [[ "$(git branch --show-current)" == "$branch" ]]; then
    git push origin "$branch"
else
    echo "you're not in the same branch" >&2
fi

