#!/usr/bin/env bash

bash ./git-automation

read -p "GitHub repository URL: " http

git remote get-url origin >/dev/null 2>&1 ||
git remote add origin "$http"

git push -u origin "$(git branch --show-current)"


